version: '3'

services:
  zookeeper:
    image: 'wurstmeister/zookeeper:latest'
    hostname: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: 'wurstmeister/kafka:latest'
    hostname: localhost
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "postTopic:1:1,commentTopic:1:1,userRegistrationTopic:1:1"

  bsocial-microservice:
    build: ./bSocial
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "3000:3000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JWT_SECRET: "your_secret_key"
      JWT_EXPIRE: "12h"

  notifications-microservice:
    build: ./NotificationsMicroservice
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "3001:3001"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"

  elasticsearch-microservice:
    build: ./ElasticSearchMicroservice
    depends_on:
      - kafka
      - zookeeper
      - elasticsearch
    command: ["dockerize", "-wait", "tcp://elasticsearch:9200", "-timeout", "600s", "npm", "start"]
    ports:
      - "3002:3002"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      ELASTICSEARCH_HOST: "http://elasticsearch:9200"
      ELASTICSEARCH_USERNAME: "ilija"
      ELASTICSEARCH_PASSWORD: "ilijaG"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    environment:
      - discovery.type=single-node        
      - ELASTICSEARCH_USERNAME=ilija
      - ELASTICSEARCH_PASSWORD=ilijaG
    ports:
      - "9200:9200"