version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    hostname: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:6.2.1
    hostname: localhost
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "postTopic:1:1,commentTopic:1:1,userRegistrationTopic:1:1"

  bsocial-microservice:
    build: ./bSocial
    # image: bsocial-image
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "3000:3000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"

  notifications-microservice:
    build: ./NotificationsMicroservice
    # image: notifications-image
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "3001:3001"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"

  elasticsearch-microservice:
    # image: elasticsearch-image
    build: ./ElasticSearchMicroservice
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "3002:3002"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"